#!/usr/bin/env bash

# Prüfen ob eine Datei als Parameter übergeben wurde.
if [ -z ${1+x} ]; then 
        echo "$0: You need to supply a tex file as argument for this script.";
        exit 1
fi

if [ ! -f "$1" ]
then
    echo "$0: File '${1}' not found."
fi

full_name=$(realpath $1)
dir=$(dirname $full_name)
filename=$(basename $1)

docker run --rm -e TEX_FILE=$filename -v $dir:/mnt/input -it b0wter/texdocker
